import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faUserCircle,
    faBars,
    faEnvelope,
    faBell,
    faUser,
    faKey,
    faAt,
    faCog,
    faSignOutAlt,
    faGlobeAmericas,
    faCaretRight,
    faCaretLeft,
    faSearch,
    faTimes,
    faUsers,
    faTrash,
    faTrashAlt,
    faUserPlus,
    faPlay,
    faEye,
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faUserCircle,
    faBars,
    faEnvelope,
    faBell,
    faUser,
    faKey,
    faAt,
    faCog,
    faSignOutAlt,
    faGlobeAmericas,
    faCaretRight,
    faCaretLeft,
    faSearch,
    faTimes,
    faUsers,
    faTrash,
    faTrashAlt,
    faUserPlus,
    faPlay,
    faEye
);
