version: "3.7"

services:
    app:
        build: ./
        restart: always
        environment:
            VIRTUAL_PORT: 8080
            VIRTUAL_HOST: streamify.ssprojects.ca
            LETSENCRYPT_HOST: streamify.ssprojects.ca
            LETSENCRYPT_EMAIL: "fastf20@gmail.com"
        networks:
            - service-network
            - streamify-network
        depends_on:
            - db

    db:
        image: postgres:11.2-alpine
        environment:
            POSTGRES_DB: streamify
            POSTGRES_USER: streamify
            POSTGRES_PASSWORD: pw
        networks:
            - streamify-network
        volumes:
            - ~/db_streamify:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    service-network:
        external: true
    streamify-network:
        driver: bridge
